use crate::{EngineError, EngineStatus, TranscriptionStatus};

/// Opaque UUID string generated by the runtime, portable across transports.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(transparent))]
pub struct SessionId(pub String);

impl std::fmt::Display for SessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SourceConfig {
    pub device_id: Option<String>,
    pub preferred_sample_rate: Option<u32>,
    pub preferred_channels: Option<u16>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SourceState {
    pub configured: SourceConfig,
    /// User preference; may be true even if the source failed to start.
    pub enabled: bool,
    /// Native stream is running. It does not promise non-silent samples.
    pub active: bool,
    pub last_error: Option<EngineError>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FeatureState {
    pub enabled: bool,
    pub available: bool,
    pub status: TranscriptionStatus,
    /// Number of input blocks discarded because the bounded speech queue was full.
    pub dropped_blocks: u64,
    #[cfg_attr(feature = "serde", serde(default))]
    pub asr: AsrMetrics,
    /// Backend/model details become available once the worker loads its model.
    #[cfg_attr(feature = "serde", serde(default))]
    pub backend: Option<String>,
    #[cfg_attr(feature = "serde", serde(default))]
    pub model: Option<String>,
    #[cfg_attr(feature = "serde", serde(default))]
    pub supports_partial_results: bool,
    #[cfg_attr(feature = "serde", serde(default))]
    pub supports_true_streaming: bool,
}

/// Integer units preserve snapshot equality and portable serialization.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AsrMetrics {
    pub input_queue_depth: usize,
    pub inferences: u64,
    pub queued_work: usize,
    pub coalesced_work: u64,
    pub dropped_work: u64,
    pub dropped_events: u64,
    pub vad_segments: u64,
    pub average_inference_ms: u64,
    pub maximum_inference_ms: u64,
    /// Average real-time factor multiplied by 1000.
    pub average_rtf_milli: u64,
}

/// Compiled backend support, not current device presence or permission grants.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EngineCapabilities {
    pub microphone_capture: bool,
    pub system_audio_capture: bool,
    pub transcription: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SessionInfo {
    pub id: SessionId,
    pub started_at_unix_ms: u64,
    /// Local path; a future remote transport must translate it if necessary.
    pub recording_directory: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EngineSnapshot {
    /// Monotonic publication revision. Elapsed time updates occur on UI ticks.
    pub revision: u64,
    pub status: EngineStatus,
    pub microphone: SourceState,
    pub system_audio: SourceState,
    pub transcription: FeatureState,
    pub capabilities: EngineCapabilities,
    /// Current session while recording; most recent session after stopping.
    pub session: Option<SessionInfo>,
    pub elapsed_ms: u64,
    pub dropped_microphone_blocks: u64,
    pub dropped_system_blocks: u64,
    pub last_error: Option<EngineError>,
}
