[package]
name = "model-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bzip2 = "0.4"
reqwest.workspace = true
serde.workspace = true
sha2.workspace = true
tar = "0.4"
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
