#import "recordings_selector.h"
#import "transcription_window.h"
extern void rimv_menu_selector_did_close(NSInteger);
@interface RimvRecordings : NSObject <NSSearchFieldDelegate, NSPopoverDelegate>
@property(nonatomic,strong) NSPopover *popover; @property(nonatomic,strong) NSArray *sessions; @property(nonatomic,strong) NSSearchField *search; @property(nonatomic,strong) NSView *list; @property(nonatomic,copy) NSString *filter;
@end
@implementation RimvRecordings
- (void)show:(NSView *)anchor { if(self.popover.shown)return; NSView *v=[[NSView alloc]initWithFrame:NSMakeRect(0,0,336,440)]; NSTextField *h=[NSTextField labelWithString:@"Recordings"]; h.frame=NSMakeRect(18,404,180,22); h.font=[NSFont systemFontOfSize:17 weight:NSFontWeightSemibold]; [v addSubview:h]; self.search=[[NSSearchField alloc]initWithFrame:NSMakeRect(18,356,300,36)]; self.search.placeholderString=@"Search recordings..."; self.search.delegate=self; [v addSubview:self.search]; self.filter=@"all"; NSArray *titles=@[@"All",@"Recording",@"Completed"]; for(NSInteger i=0;i<3;i++){ NSButton*b=[NSButton buttonWithTitle:titles[i] target:self action:@selector(filter:)]; b.tag=i; b.frame=NSMakeRect(18+i*94,320,88,25); [v addSubview:b]; } NSScrollView*s=[[NSScrollView alloc]initWithFrame:NSMakeRect(18,50,300,260)]; s.hasVerticalScroller=YES; self.list=[[NSView alloc]initWithFrame:NSMakeRect(0,0,300,1)]; s.documentView=self.list; [v addSubview:s]; NSButton*folder=[NSButton buttonWithTitle:@"Open Recordings Folder" target:self action:@selector(folder:)]; folder.frame=NSMakeRect(18,14,180,28); [v addSubview:folder]; NSViewController*c=[NSViewController new]; c.view=v; self.popover=[NSPopover new]; self.popover.behavior=NSPopoverBehaviorApplicationDefined; self.popover.delegate=self; self.popover.contentSize=v.bounds.size; self.popover.contentViewController=c; [self reload]; [self.popover showRelativeToRect:anchor.bounds ofView:anchor preferredEdge:NSRectEdgeMaxX]; }
- (void)filter:(NSButton*)b { self.filter=@[@"all",@"recording",@"completed"][b.tag]; [self reload]; }
- (void)controlTextDidChange:(NSNotification*)n { (void)n; [self reload]; }
- (void)reload { for(NSView*v in self.list.subviews.copy)[v removeFromSuperview]; NSString*q=self.search.stringValue.lowercaseString ?: @""; CGFloat y=0; NSInteger count=0; for(NSDictionary*s in self.sessions){ if(![self.filter isEqual:@"all"] && ![s[@"state"] isEqual:self.filter])continue; NSString*name=s[@"name"] ?: @"Recording"; if(q.length && ![name.lowercaseString containsString:q])continue; NSButton*b=[NSButton buttonWithTitle:[NSString stringWithFormat:@"%@  %@",name,s[@"detail"]?:@""] target:self action:@selector(open:)]; b.identifier=s[@"path"]; b.frame=NSMakeRect(0,y,292,42); b.bordered=NO; b.alignment=NSTextAlignmentLeft; [self.list addSubview:b]; y+=46; count++; } if(!count){ NSTextField*e=[NSTextField labelWithString:@"No recordings match."]; e.frame=NSMakeRect(8,12,270,22); [self.list addSubview:e]; y=50; } self.list.frame=NSMakeRect(0,0,300,y); }
- (void)open:(NSButton*)b { NSDictionary*s=[self.sessions filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"path == %@",b.identifier]].firstObject; if([s[@"state"] isEqual:@"recording"]) rimv_transcription_window_open(); else if(b.identifier.length) rimv_transcription_window_open_session(b.identifier.UTF8String); }
- (void)folder:(id)x { (void)x; NSString*p=self.sessions.firstObject[@"root"]; if(p)[[NSWorkspace sharedWorkspace]openURL:[NSURL fileURLWithPath:p isDirectory:YES]]; }
- (void)popoverDidClose:(NSNotification *)notification { if(notification.object!=self.popover)return; rimv_menu_selector_did_close(3); }
@end
static RimvRecordings *rs; static NSArray* parse(const char*j){ if(!j)return @[]; id x=[NSJSONSerialization JSONObjectWithData:[[NSString stringWithUTF8String:j]dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil]; return [x isKindOfClass:NSArray.class]?x:@[]; }
void rimv_recordings_selector_update(const char*j){ NSArray*x=parse(j); dispatch_async(dispatch_get_main_queue(),^{ if(!rs)rs=[RimvRecordings new];rs.sessions=x;[rs reload];});}
void rimv_recordings_selector_show(NSView*a){ if(!rs)rs=[RimvRecordings new]; [rs show:a]; }
bool rimv_recordings_selector_contains_window(NSWindow *window){ return rs.popover.shown && rs.popover.contentViewController.view.window == window; }
bool rimv_recordings_selector_is_shown(void){ return rs.popover.shown; }
void rimv_recordings_selector_close(void){ [rs.popover performClose:nil]; }
